apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgresql
    type: postgres
    access: proxy
    url: timescale:5432
    database: quantumleap
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 903
      timescaledb: true
      minInterval: 1m
    isDefault: true
    editable: true